export const itemData = [
  {
    img: "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
    title: "Burger",
  },
  {
    img: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
    title: "Camera",
  },
  {
    img: "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
    title: "Coffee",
  },
  {
    img: "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
    title: "Hats",
  },
  {
    img: "https://i.pinimg.com/736x/d7/a0/fb/d7a0fb1fd09ad171ebb6395faed1ad77.jpg",
    title: "Honey",
  },
  {
    img: "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
    title: "Basketball",
  },
  {
    img: "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
    title: "Honey",
  },
  {
    img: "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
    title: "Fern",
  },
  {
    img: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
    title: "Mushrooms",
  },
  {
    img: "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
    title: "Tomato basil",
  },
  {
    img: "https://images.pexels.com/photos/17636489/pexels-photo-17636489/free-photo-of-man-in-hat-and-with-backpack-standing-with-hills-behind.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    title: "Sea star",
  },
  {
    img: "https://uhdwallpapers.org/uploads/cache/3303916991/travel-through-paris_600x338-mt-90.jpg",
    title: "Bike",
  },
  {
    img: "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
    title: "Burger",
  },
  {
    img: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
    title: "Camera",
  },
  {
    img: "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
    title: "Coffee",
  },
  {
    img: "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
    title: "Hats",
  },
  {
    img: "https://i.pinimg.com/736x/d7/a0/fb/d7a0fb1fd09ad171ebb6395faed1ad77.jpg",
    title: "Honey",
  },
  {
    img: "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
    title: "Basketball",
  },
  {
    img: "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
    title: "Honey",
  },
  {
    img: "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
    title: "Fern",
  },
  {
    img: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
    title: "Mushrooms",
  },
  {
    img: "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
    title: "Tomato basil",
  },
  {
    img: "https://images.pexels.com/photos/17636489/pexels-photo-17636489/free-photo-of-man-in-hat-and-with-backpack-standing-with-hills-behind.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    title: "Sea star",
  },
  {
    img: "https://uhdwallpapers.org/uploads/cache/3303916991/travel-through-paris_600x338-mt-90.jpg",
    title: "Bike",
  },
];

export const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person:
      "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person:
      "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person:
      "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTho7_3HhPBjQdPnFAx5JnjWR3ae7lrTcvk9w&usqp=CAU",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 8,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person:
      "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
  },
  {
    id: 9,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
  },
  {
    id: 10,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person:
      "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
  },
  {
    id: 11,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person:
      "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
  },
  {
    id: 12,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTho7_3HhPBjQdPnFAx5JnjWR3ae7lrTcvk9w&usqp=CAU",
  },
  {
    id: 13,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 14,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 15,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 16,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 17,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 18,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 19,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 20,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 21,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 22,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person:
      "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
  },
  {
    id: 23,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
  },
  {
    id: 24,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person:
      "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
  },
  {
    id: 25,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person:
      "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
  },
  {
    id: 26,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTho7_3HhPBjQdPnFAx5JnjWR3ae7lrTcvk9w&usqp=CAU",
  },
  {
    id: 27,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 28,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 29,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 30,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 31,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 32,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 33,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 34,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 35,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 36,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person:
      "https://bestideadiy.com/wp-content/uploads/2023/06/best-friends-day.jpg",
  },
  {
    id: 37,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "https://www.nawpic.com/media/2020/bff-for-2-nawpic-4.jpg",
  },
  {
    id: 38,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person:
      "https://c1.wallpaperflare.com/preview/1024/496/939/best-friends-sunset-beach-jumping.jpg",
  },
  {
    id: 39,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person:
      "https://images.pexels.com/photos/2916828/pexels-photo-2916828.jpeg?cs=srgb&dl=pexels-andre-furtado-2916828.jpg&fm=jpg",
  },
  {
    id: 40,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTho7_3HhPBjQdPnFAx5JnjWR3ae7lrTcvk9w&usqp=CAU",
  },
  {
    id: 41,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person:
      "https://www.kinghillstravels.com/uploads/tour_package/0lu6tfEK2w.jpg",
  },
  {
    id: 42,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 43,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 44,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 45,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 46,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
  {
    id: 47,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person:
      "https://pikwizard.com/pw/small/090fe3c0bc7abe0a340b31e82e30b5f9.jpg",
  },
];
